CREATE TABLE take(
  driverId INT NOT NULL,
  passengerId INT NOT NULL,
  tripId INT NOT NULL,
  twoWay BOOLEAN,
  PRIMARY KEY(driverId, passengerId, tripId),
  FOREIGN KEY(driverId) REFERENCES Person (personId)
  ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY(passengerId) REFERENCES Person (personId)
  ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (tripId) REFERENCES Trip (tripId)
  ON DELETE CASCADE ON UPDATE CASCADE)
ENGINE = InnoDB;